# Generated by Django 2.2 on 2020-03-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200305_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='posts',
            new_name='post',
        ),
    ]
