# Generated by Django 2.2 on 2020-03-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200305_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='updated',
        ),
    ]
