# Generated by Django 2.2 on 2020-03-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_events_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='created',
            new_name='Date',
        ),
    ]
