# Generated by Django 2.2 on 2020-03-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('admin_no', models.IntegerField()),
                ('langauges', models.CharField(choices=[('PYTHON', 'PYTHON'), ('JAVA', 'JAVA'), ('NODE', 'NODE'), ('ANGULAR', 'ANGULAR'), ('ARDUINO', 'ARDUINO'), ('PHP', 'PHP'), ('REACT', 'REACT'), ('HTML', 'HTML'), ('SECURITY', 'SECURITY'), ('NETWORKS', 'NETWORKS'), ('DATASCIENCE', 'DATASCIENCE')], max_length=50)),
                ('team', models.CharField(choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('TEAM', 'TEAM')], max_length=60)),
                ('idea', models.FileField(upload_to='documents/')),
                ('bio', models.TextField()),
            ],
        ),
    ]
